# Server configurations
# Bot token from telegram botfather.
server:
  token: ""
  # Log level (0 - Trace, 1 - Debug, 2 - Info, 3 - Warn, 4 - Error, 5 - Fatal)
  logLevel: ""

accountinfo:
  iban: ""
  swift: ""
  name: ""